### ISSUE TITLE
No flag registered for --command-type

### ISSUE THREAD

**Issue by OwenVey** [bloomberg/stricli#10]
**Describe the bug**
When running `npx @stricli/create-app@latest --command-type single` as shown [here](https://bloomberg.github.io/stricli/docs/tutorial/#single-command), I get an error stating the following:
```
No flag registered for --command-type
```

**To Reproduce**
Run `npx @stricli/create-app@latest --command-type single`

**Expected behavior**
A single command app is properly generated.

**Screenshots**
<img width="413" alt="Screenshot 2024-10-01 at 10 45 44 AM@2x" src="https://github.com/user-attachments/assets/7b422ff1-e574-4405-9190-05e0e55e8e3f">

**Environment (please complete the following information):**
 - Operating System and Version: MacOS Sequoia 15.0
 - Browser [e.g. Firefox, Safari] (if applicable): N/A

**Comment by molisani** [comment]
Ah sorry, that's a typo. It was renamed from --command-type to --template in the tool but not in the tutorial, will fix.
