### ISSUE TITLE
DOCS: include yargs in the alternative tools

### ISSUE THREAD

**Issue by dvidsilva** [bloomberg/stricli#15]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
A short paragraph talking about yargs 

**Describe alternatives you've considered**
i'm opening a pull request right after this

**Additional context**
yargs has a cool logo 

![](https://yargs.js.org/images/yargs-logo.png)

**Comment by molisani** [comment]
Resolved by #16
