### ISSUE TITLE
Support command examples

### ISSUE THREAD

**Issue by akuntsch** [bloomberg/stricli#20]
**Is your feature request related to a problem? Please describe.**
The problem of not being able to provide full command examples with descriptions.

**Describe the solution you'd like**
Support command examples with descriptions and show them in the auto-generated help text.

I'm thinking of something like this:
```typescript
buildCommand({
  ...
  docs: {
    examples: [
      { command: 'mycommand --flag1 value1 ....', description: 'Does this and that' },
      ...
    ],
    ...
  },
  ...
});
```

Might also use an array of arrays like some other frameworks do, but I personally prefer explicit properties.

The generated help text should then have an `EXAMPLES` section where the examples are shown.

**Describe alternatives you've considered**
I tried using `customUsage` but there's not really a way to get the desired result with that.

**Additional context**
This feature is supported by many other cli frameworks and can be pretty useful imo.

**Comment by molisani** [comment]
This is a good idea, but I wonder if there would be some way to enhance the usage section to have documented use cases. I think having USAGE and EXAMPLES is a bit too repetitive and the existing USAGE section could use some more customizability.
