### ISSUE TITLE
How to reuse flags/aliases in multiple commands

### ISSUE THREAD

**Issue by akuntsch** [bloomberg/stricli#22]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want an easy way to share common flags and aliases across multiple commands with proper type checking.

**Describe alternatives you've considered**
I have tried the following, which seems to work pretty well, but only when I export the `TypedCommandFlagParameters` type (which is currently not exported).

Define the base flag interface and definition:
```typescript
// common-flags.ts
export interface CommonFlags {
    myFlag: boolean;
}

export const commonFlagsDefinition: TypedCommandFlagParameters<Readonly<CommonFlags>, CommandContext> = {
    flags: {
        myFlag: {
            kind: 'boolean',
            brief: 'whatever',
            default: false,
        },
    },
    aliases: {
        f: 'myFlag',
    },
};
```

Then extend the common interface and spread the definition into the command builder:
```typescript
// command.ts
import { type CommonFlags,  commonFlagsDefinition } from './common-flags';

export interface MyCommandFlags extends CommonFlags {
    myRealFlag: boolean;
}

export const myCommand = buildCommand({
    loader: async () => import('...'),
    parameters: {
        flags: {
            ...commonFlagsDefinition.flags,
            myRealFlag: { ... }
        },
        aliases: {
            ...commonFlagsDefinition.aliases,
            r: 'myRealFlag',
        },
    },
});
```

Is there a better way or a pattern to use to achieve the same?

**Additional context**
None

**Comment by molisani** [comment]
For your use case I think you could use the currently exported type `FlagParametersForType` to come up with a type of the config object for your `CommonFlags`.

```ts
export const commonFlags: FlagParametersForType<Readonly<CommonFlags>> = {
    myFlag: {
        kind: 'boolean',
        brief: 'whatever',
        default: false,
    },
};
```

But yes you're right that it would be easier to define this with the `TypedCommandFlagParameters` all at once but that isn't exported. We should change the library to export that type (along with the `Aliases`) type.

**Comment by akuntsch** [comment]
Yea, I've tried with the `FlagParametersForType` type before but that's only for flags and not aliases as well. I think there was also some kind of error when merging that into the final command, but I can't remember.

Exporting `TypedCommandFlagParameters` would be sweet. Thanks!

For now I just copied the type and other needed types to a local file and use that.
