### ISSUE TITLE
Update documentation for positional argument to mention placeholder

### ISSUE THREAD

**Issue by rkofman** [bloomberg/stricli#23]
First off, I have to say that I *love* this framework and how opinionated it is about its design philosophy. <3 <3 <3

**Problem Statement**
Right now, the positional arguments are always named `arg1`, `arg2`, etc. For example:
```
move <arg1> <arg2>
```
This can make for unintuitive user experience, needing to look down in the args definition for more context:
```
ARGUMENTS
  arg1   source file
  arg2   destination file
```

**Proposed Solution**
But it would be useful to be able to name the parameters, so the help message could be:
```
move <from> <to>
```

Which also creates a slightly more readable arguments list:
```
ARGUMENTS
  from   source file
  to   destination file
```

**Comment by molisani** [comment]
Actually, this is already supported 😄 

The property is called `placeholder` as it acts as a placeholder in the generated usage line and documentation.

```diff
  positional: {
    kind: "tuple",
    parameters: [
      {
        brief: "source file",
        parse: String,
+       placeholder: "from"
      },
      {
        brief: "destination file",
        parse: String,
+       placeholder: "to"
      },
    ],
  },
```

which produces the following output

```
ARGUMENTS
  from  source file
  to    destination file
```

If you don't mind, I'll leave this issue open and refocus it to enhance the documentation for this setting.
